#!/usr/bin/env python

# Script to create a new boinc user and give submit right

import os
from Boinc.database import connect, App
from Boinc.db_base import get_dbconnection
from Boinc.configxml import ConfigFile
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("user", help="User to grant submit right",
                    type=str)
parser.add_argument("--quota", help="User priority when resources are scarse (default 100)",
                    default=100, type=int)
parser.add_argument("--max_jobs", help="Max number of concurrent running jobs for this user",
                    default=0, type=int)
args = parser.parse_args()


config = ConfigFile().read()

# connect to database
connect()
dbcon = get_dbconnection()
cursor = dbcon.cursor()
cursor.execute("use %s"%config.config.db_name)

# get user id
cursor.execute(f"select id,authenticator from user where name=\"{args.user}\"")
res = cursor.fetchall()[0]
user_id, auth = res['id'], res['authenticator']

# grant user submit
req = f"INSERT INTO user_submit VALUES ({user_id},{args.quota},0,1,1,{args.max_jobs});"
cursor.execute(req)
dbcon.commit()
cursor.close()

# return authenticator
print(auth)
