#!/usr/bin/env python

# Script to create apps in the database while reading /boinc_project_root/apps

import os
from Boinc.database import connect, App
from Boinc.db_base import get_dbconnection
from Boinc.configxml import ConfigFile


config = ConfigFile().read()

# list current apps
apps = os.listdir("apps")
apps = [x for x in apps if os.path.isdir(f"apps/{x}")]

# connect to database
connect()
dbcon = get_dbconnection()
cursor = dbcon.cursor()

cursor.execute("use %s"%config.config.db_name)
cursor.execute("select name from %s"%App._table.table)
names = [x["name"] for x in cursor.fetchall()]

apps = [x for x in apps if x not in names]
print("Adding new apps", apps)

for app in apps:
    args = {
        "create_time": "0",
        "name": f"\"{app}\"",
        "min_version": "0",
        "deprecated":"0",
        "user_friendly_name":f"\"{app}\"",
        "homogeneous_redundancy":"0",
        "weight":"1",
        "beta":"0",
        "target_nresults":"0",
        "min_avg_pfc":"1",
        "host_scale_check":"0",
        "homogeneous_app_version":"0",
        "non_cpu_intensive":"0",
    }
    columns = ",".join(args.keys())
    values = ",".join(args.values())
    
    req = f"INSERT INTO {App._table.table} ({columns}) VALUES ({values})"
    cursor.execute(req)

dbcon.commit()
cursor.close()

